# @Author: Muhammad Umair
# @Date:   2022-06-20 09:12:20
# @Last Modified by:   Muhammad Umair
# @Last Modified time: 2022-06-29 14:25:36


name : "2.0-GPT-Finetune-CustomDataset-HPC"
root : "/cluster/tufts/deruiterlab/mumair01/projects/gpt_monologue_dialogue"
# Input data dirs.
dataset:
  name : "in_conversation_corpus_poc"
  type : "csv"
  train_path : "data/processed/in_conversation_corpus_poc/train.csv"
  val_path : "data/processed/in_conversation_corpus_poc/validation.csv"
  custom : true
# Result paths
results:
  save_model_dir : "models/gpt_finetune_script/customDataset"
  reports_dir : "reports/gpt_finetune_script/customDataset"
# Training args
training:
    num_train_epochs : 30
    per_device_train_batch_size : 16
    per_device_eval_batch_size : 16
    eval_steps : 200
    save_steps : 400
    warmup_steps : 300


