# @Author: Muhammad Umair
# @Date:   2022-06-20 09:12:20
# @Last Modified by:   Muhammad Umair
# @Last Modified time: 2022-06-22 13:51:16


name : "huggingface_gpt_finetune"
root : "/Users/muhammadumair/Documents/Repositories/mumair01-repos/GPT-Monologue-to-Dialogue"
# Input data dirs.
dataset:
  name : "in_conversation_corpus_poc"
  type : "csv"
  train_path : "data/processed/in_conversation_corpus_poc/train.csv"
  val_path : "data/processed/in_conversation_corpus_poc/validation.csv"
# Result paths
results:
  save_model_dir : "models/gpt_finetune_script"
  reports_dir : "reports/gpt_finetune_script"
# Training args
training:
    num_train_epochs : 1
    per_device_train_batch_size : 2
    per_device_eval_batch_size : 2
    eval_steps : 1
    warmup_steps : 1


