# @Author: Muhammad Umair
# @Date:   2022-07-06 15:33:03
# @Last Modified by:   Muhammad Umair
# @Last Modified time: 2022-07-14 12:26:50


env:
  name : gpt2_large_ICC_experiment_28_train_14_test_07-12-2022_16-55-36_customDataset_speaker_identity_stims
  root :  /cluster/tufts/deruiterlab/mumair01/projects/gpt_monologue_dialogue
  seed : null
dataset :
  path : data/datasets/processed/speaker_identity_stims/test.csv
  start_conversation_no : 0
  end_conversation_no : -1
results:
  save_dir : data/reports/2.0-ConditionalProb-Inference-HPC
inference:
  model_checkpoint : /cluster/tufts/deruiterlab/mumair01/projects/gpt_monologue_dialogue/data/models/2.0-GPT-Finetune-CustomDataset-HPC/gpt2_large_ICC_experiment_28_train_14_test_07-12-2022_16-55-36/trainer/checkpoint-672
  tokenizer_checkpoint : gpt2 # NOTE: Should be replaced with training tokenizer
  tokenizer_additional_special_tokens :
    - <SP1> # Speaker 1 token
    - <SP2> # Speaker 2 token
    - <START> # Conversation start token
    - <END> # Conversation end token
  n_probs : -1
  context_buffer_size : 512
