# @Author: Muhammad Umair
# @Date:   2022-07-06 15:33:03
# @Last Modified by:   Muhammad Umair
# @Last Modified time: 2022-07-08 11:24:23


env:
  name : 1.0-Surprisal-Inference-HPC
  root :  /cluster/tufts/deruiterlab/mumair01/projects/gpt_monologue_dialogue
  seed : null
dataset :
  path : data/datasets/processed/ICC/julia_dissertation/test.csv
  start_conversation_no : 0
  end_conversation_no : -1
results:
  save_dir : data/reports/2.0-ConditionalProb-Inference-HPC
inference:
  model_checkpoint : /cluster/tufts/deruiterlab/mumair01/projects/gpt_monologue_dialogue/models/gpt_finetune_script/textDataset/07-06-2022_16-55-08/trainer/checkpoint-756 # NOTE: Should be replaced with finetuned model
  tokenizer_checkpoint : gpt2 # NOTE: Should be replaced with training tokenizer
  tokenizer_additional_special_tokens :
    - <SP1> # Speaker 1 token
    - <SP2> # Speaker 2 token
    - <START> # Conversation start token
    - <END> # Conversation end token
  n_probs : -1
  context_buffer_size : 512
