hydra:
  run:
    # Ex output dir: .../outputs/finetune/turngpt_icc_5_train_37_test/2022-08-10_141516
    dir: ${env.paths.root}/outputs/${experiment.name}/${experiment.model_name}_${dataset.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: True


# # Composing nested config with default
# defaults:
#   - env : local
#   - dataset : null

#   - override hydra/job_logging: colorlog
#   - override hydra/hydra_logging: colorlog