# @Author: Muhammad Umair
# @Date:   2022-06-20 09:12:20
# @Last Modified by:   Muhammad Umair
# @Last Modified time: 2022-07-08 11:41:57


name : 2.0-GPT-Finetune-CustomDataset-HPC
root : /cluster/tufts/deruiterlab/mumair01/projects/gpt_monologue_dialogue
env:
  seed : null
# Input data dirs.
dataset:
  name : in_conversation_corpus_poc
  train_path :data/datasets/processed/ICC/julia_dissertation/train.csv
  val_path : data/datasets/processed/ICC/julia_dissertation/validation.csv
  custom : false
# Result paths
results:
  save_dir : data/models/2.0-GPT-Finetune-CustomDataset-HPC/customDataset
  reports_dir : data/models/2.0-GPT-Finetune-CustomDataset-HPC/customDataset
# Training args
training:
    model_checkpoint : gpt2-large
    # model_checkpoint : distilgpt2
    tokenizer_checkpoint : gpt2
    tokenizer_additional_special_tokens :
      - <SP1> # Speaker 1 token
      - <SP2> # Speaker 2 token
      - <START> # Conversation start token
      - <END> # Conversation end token
    data_block_size : 128
    num_train_epochs : 30
    per_device_train_batch_size : 16
    per_device_eval_batch_size : 16
    warmup_steps : 300





